name: Release dogfood

on:
  workflow_dispatch:

env:
  java_version: 17

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: Dogfood

    strategy:
      matrix:
        include:
          - name: Main APK
            gradle-command: app:assembleRelease
            result: app/build/outputs/apk/release/*.apk

    name: ${{ matrix.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create secrets
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > app/ci-signing.jks
          echo "${{ secrets.LOCAL_PROPERTIES }}" > app/local.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.java_version}}
          distribution: temurin

      - name: Build ${{ matrix.name }}
        run: ./gradlew ${{ matrix.gradle-command }} --stacktrace
